---
title: "Quality Assurance Report"
author: "Shazmeen Maroof"
date: now
execute:
  echo: false
format:
  html:
    embed-resources: true
    toc: true
    toc-title: "Contents"
    toc-location: left
    html-math-method: katex
---

```{python}
# Importing libraries and reading data
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

housing_introduction = pd.read_excel("D:\\git_demo\\Data/Housing_data.xlsx", sheet_name="introduction")

housing_sale_counts = pd.read_excel("D:\\git_demo\\Data/Housing_data.xlsx", sheet_name="sale_counts")

housing_mean_sale_price = pd.read_excel("D:\\git_demo\\Data/Housing_data.xlsx", sheet_name="mean_sale_price")

# Read total number of rows and columns in the data
nrow, ncol = housing_sale_counts.shape
```

## Introduction

```{python}
display(Markdown(f""" The title of the dataset is {housing_introduction.at[0, 'Column_b']}. {housing_introduction.at[1, 'Column_b']}. The data has been taken from {housing_introduction.at[2, 'Column_b']}. The data is published {housing_introduction.at[3, 'Column_b']}. The data covers {housing_introduction.at[4, 'Column_b']}. The data limitations are {housing_introduction.at[5, 'Column_b']}. The data is published {housing_introduction.at[7, 'Column_b']} confidence intervals. {housing_introduction.at[8, 'Column_b']}. There are {nrow} rows and {ncol} columns in the dataset. """))
``` 


## Data quality tests   

## Test 1  
Description: Checks if sum of variables equals total.  
Data specific description: Checks if sum of detahced, semi-detached, terraced houses and flats equals all dwelling types

```{python}
def test_sum_variables():
    if all(housing_sale_counts[(housing_sale_counts['All_dwelling_types']) != (housing_sale_counts['Detached'] + housing_sale_counts['Semi-detached'] + housing_sale_counts['Terraced'] + housing_sale_counts['Flats'])]):
        print("Status: Fail. A fail means sum of varaibles do not equal total.")
        return False
    else:
        print("Status: Pass. A pass means sum of variables equals total.")
        return True
print (test_sum_variables())

housing_sale_counts[(housing_sale_counts['All_dwelling_types']) != (housing_sale_counts['Detached'] + housing_sale_counts['Semi-detached'] + housing_sale_counts['Terraced'] + housing_sale_counts['Flats'])]

```

## Test 2  

Description: Checks if values of a variable are always less than other.  
Data specific description: Checks if the number of flats are lesser than the number of semi-detached houses.

```{python}
def test_val_variable():
    if all(housing_sale_counts[(housing_sale_counts['Semi-detached']) <(housing_sale_counts['Flats'])]): 
        print("Status: Fail. A fail means number of flats are not less than number of semi-detached houses in atleast one LA.")
        return False
    else:
        print("Status: Pass. A pass means number of flats are less than number of semi-detached houses in all LAs")
        return True
print (test_val_variable())

housing_sale_counts[(housing_sale_counts['Semi-detached']) < (housing_sale_counts['Flats'])]
```

## Test 3  

Description: Checks if any of the variables in the dataset has a negative value.
Data specific description: Checks if the data on sales of detahced, semi-detached, terraced and flats has a negative value. 
```{python}
test_neg = ((housing_sale_counts['Detached' or 'Semi-detached' or 'Terraced' or 'Flats']) < 0).any()
print ("Status:")
print (test_neg)
print("Status description: A true means there is a negative values (Fail). A false means there is no negative value (Pass).")

housing_sale_counts[((housing_sale_counts['Flats']) < 0)]
```

## Test 4

Description: Checks if any of the variables in the dataset has a missing value.
Data specific description: Checks if the data on prices of detahced, semi-detached, terraced and flats has a missing value. 
```{python}
display(Markdown(f"""Status: There are {housing_sale_counts.isnull().values.sum()} missing values in the dataset.  """))

housing_sale_counts[housing_sale_counts['Detached'].isnull()]
``` 

## Test 5
Description: Checks if any values of the variables in the dataset contains a letter.  
Data specific description: Checks if the data on sales of detahced, semi-detached, terraced and flats has a non-numeric value.  
Status: 
```{python}

```

## Test 6  
Description: Checks if a certain value appears specific times in data.  
Data specific description: Checks if a local authority name appears only 5 times in the dataset.  
 Status: 
```{python}
```

## Test 7  
Description: Checks if the value of a variable is increasing over time. 
Data specific description: Total sale price of each dwelling type in time 't' should be less than time 't+1'.
Status: 

check if a series has the same data type, like number, letters, date etc
## Data characteristics' tests

Test 1: Plot trend of sales and prices by dwelling types

Test 2: What does the data distribution look like? 

Test 3: Are there any outliers?

Test 4: Is there any correlation between tpe of dwellings and house price?
