---
title: "Guidance on Quality Questions"
author: "Shazmeen Maroof"
format: 
  html:
    page-layout: full
    css: style.css
output:
    html_document
---

# Introduction  
This guidance provide set of questions to help analytical and statistical teams evaluate the quality of their analysis throughout the production cycle. 

The aim of producing this guidance is:  
1. To ensure there is a consistent QA approach across divisions/departments.  
2. To help teams comply with best practice guidance by promoting the use of AQUA book and Code of Practice for Statistics.  
3. To ensure there is a consistent understanding of quality across the team.  
4. To encourage them producing important project documentation i.e., assumptions’ log, decision log, risk register etc.  
4. Sign post users towards relevant resources for evaluating quality. 

## Similar Guidance

This guidance has heavily refernced text from AQUA book and Code of Practice for Statistics. Two other guduances have motivated us to produce this. One is analysis function guidance on 'Quality questions and red flags' and the other is OSR guidance on 'Thinking about quality when producing statistics'. 

## How is this guidance different?

Building on the cross-government resources on best practice, this gudiance takes one step further by separating the quality questions relevant for each stage of analysis. The quality questions will only be fit for purpose if they are asked at the right stage, once that stage is passed, it will be difficult going back and addressing the risks.  

Quality questions are also separated as per the responsible individuals required for answering them. The idea is to highlight a clear line of accountability as per AQUA book guidance in an easy-to-understand manner. The hope is to make it easier for the teams to clearly see the AQUA roles.  

Each question is linked with the Code of Practice for Statistics (pillars and practices). This is to help the users understand the pillars and practices of Code of Practices covered by the quality question.  

## When to use this guidance?
We encourgae all teams starting to work on a new piece of analysis to maintain the log of answers using this templates. For teams, who have already, they can still think backwards for the questions asked at the scope and design stage. Teams can also use it in undersatnding the AQUA roles and Code of Practice.

## Structure 

There are 60 questions in total covering all stages of analytical cycle. AQUA book has divided the stages of analytical cycle into 1) Scoping, 2) Design, 3) Conducting and checking analysis and 4) Delivery  
We tried to be consitent in the use of terminology by sticking with these stages.  

Each stage is divided into the following tabs:

### AQUA roles  
In order to ensure that the responsibilities required to deliver analysis that is fit-for-purpose, AQUA book identifies a framework with 3 important roles: the commissioner, the analyst and the analytical assurer. Moreover, there has to be an SRO.


Responsibilities of Commissioner  
* Ensures that context is understood so QA is appropriate and proportionate  
* Ensures that there is enough time and resource for required assurance and account for risk  
* Must understand strengths and limitations including uncertainty so results are interpreted correctly  
* Delivers QUALITY OF OUTCOME

Responsibilities of Analyst  
* Assist the commissioner in framing the question to ensure the right analysis is done  
* Manage external specialists  
* Design, build, document and run the analysis  
* Delivers QUALITY OF CONTENT

Responsibilities of Analytical Assurer  
* Ensures that the evidence is there to demonstrate that appropriate QA has happened and uncertainty is communicated appropriately  
* Advises the commissioner on whether appropriate QA has happened and about any outstanding risks  
* Involved throughout from design through to use  
* Delivers QUALITY OF PROCESS

Responsibilities of SRO  
* A Single Responsible Owner for each model throughout its lifecycle

For the purpose of this guidance, it would be useful if all teams identify commissioner, analytical assurer, analyst and SRO. There main duties are described below: 

* Attach a link to AQUA book

### Code of Practice for Statistics
There are three pillars of Code of Practice for Statistics i.e., Trustworthiness, Quality and Value. Each pillar has 4 to 8 principes. 

* Attach a link to Code of Practice for Statistics
### Log of Answers  
We encourage teams to answer all questions in the tab 'Log of Answers' and save a copy on your machine. Anyone having the HTML file will be able to edit answers and the answers can be copied from this HTML to be in other files. As you will be saving the log of answers on your machine, people who don't have access to your HTML file will not ne able to see your answers. 
Answering 60 questins may seem a daunting task but this log of answers will later save your time on reading and fully undertsanding AQUA book and in ensuring your analysis/statistics complies with Code of Practice. It would also help you in writing the analysis/output report along the way. Moreover, most of the answers would help you in producing other important documents, for example, assumptions’ log, decision log, technical guide for users etc. 

### SRO sign-off


## Caveats
Missed responsibilities in AQUA book, missed principles from Code of Practice, how relevant are the stated principles for non-official stats, ad-hoc requests, experimental statistics.


# Stages


## I. Scoping

::: {.panel-tabset}

## Importance 

| Quality Questions | Why do I need to know the answer to this? | 
|---------|:-----|
| What question is the analysis trying to answer?     | A clear understanding of the question is essential for your team to scope out requirements, in understanding the strengths and limitations of the analysis and ensuring that it is fit for purpose. If the question is unclear this risks performing an analysis which does not meet the required user needs.  |   
| Why do we need to answer this question? | Exploring and understanding the need for, purpose of and end use of analysis will help you to understand the importance and impact of your work, how it supports decision making and how others will use it. It will also help you to make sure that all stages of analysis are fit for purpose and that the final output correctly answers the question you began with.  |
| Is the model business critical?   | Identifying if the model is business critical helps to define the level of assurance needed to ensure it is fit for purpose. |




<table width="100%" border="0" cellspacing="0" cellpadding="0" style="border-collapse: collapse;">
    <th> Quality Questions</th>
    <th> Why do I need to know the answer to this?</th>

  </tr style="border-bottom: 1px solid black;">
  <tr>

  <td>What
  question is the analysis trying to answer?</td>
  <td>A clear understanding of
  the question is essential. It enables your team to scope out requirements,
  understand the strengths and limitations of the analysis and ensure that it
  is fit for purpose.<br>
    If the question is unclear you risk designing and delivering analysis which
  does not meet user needs.</td>
 </tr>
 <tr>
  <td>Why
  do we need to answer this question?</td>
  <td>Exploring and understanding
  the need for, purpose of and end use of analysis will help you to understand
  the importance and impact of your work, how it supports decision making and
  how others will use it. It will also help you to make sure that all stages of
  analysis are fit for purpose and that the final output correctly answers the
  question you began with.<span style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6932690 width=315 style='height:100.0pt;width:236pt'>Which
  organisational priorities does this work address?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Setting out how the work
  aligns with organisational priorities helps you to understand how the work
  fits with wider strategic objectives and how important it is to carry out the
  analysis now. It informs the level of assurance needed to make sure the work
  is fit for purpose.</td>
 </tr>
 <tr height=200 style='height:150.0pt'>
  <td height=200 class=xl6932690 width=315 style='height:150.0pt;width:236pt'>Is
  the model business critical?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Identifying if the model is
  business critical helps to define the level of assurance needed to ensure it
  is fit for purpose.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6632690 width=315 style='height:62.5pt;width:236pt'>Who
  needs to know the answer?</td>
  <td class=xl6632690 width=396 style='width:297pt'>If you don’t know what your
  outputs will be used for, you cannot be sure that they will meet user needs.
  A good understanding of likely use cases and how you prioritise them is an
  essential part of making sure that all parts of your analysis are fit for purpose.</td>
 </tr>
 <tr height=172 style='mso-height-source:userset;height:129.0pt'>
  <td height=172 class=xl6632690 width=315 style='height:129.0pt;width:236pt'>Who
  do we need to consult to make sure we meet the right user needs?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Analysis must be well
  understood by relevant users, or else risks scope creep and misspecification.
  You should identify stakeholders and users who should be consulted before
  designing an analysis and take account of their views and considerations<span
  style='mso-spacerun:yes'>  </span>wherever relevant. Consulting the right
  stakeholders makes sure that your team and your users have a shared
  understanding and vision of what is the best way to approach answering the
  question, what the output should look like, how well the users understand the
  process, its quality and limitations, and what can be done to tailor the
  final ouput to best meet user needs.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6732690 width=315 style='height:87.5pt;width:236pt'>How
  will you know you have answered this question correctly?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Being clear about the
  outputs required and the level of error that is acceptable is essential for
  ensuring that the final output is accurate and reliable and that users and
  your team have a good understanding of limitations and uncertainty. It is
  also essential when designing verification and validation activities that
  will help you to check the robustness of results under a range of plausible
  assumptions about methods and data.</td>
 </tr>
 <tr height=183 style='height:137.5pt'>
  <td height=183 class=xl6732690 width=315 style='height:137.5pt;width:236pt'>What
  is the estimated time and resource required to answer this question (in
  months)?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Without a clear
  understanding of time and resource constraints, you may overcommit. It is
  important to push back against unrealistic demands if the team is not able to
  set aside sufficent time to effectively quality assure the analysis. The
  users and commissioner should fully understand and accept the associated
  risks to quality when time and resource pressures are unavoidable and will
  mean that there are unavoidable risks to quality.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6932690 width=315 style='height:100.0pt;width:236pt'>What
  are the consequences if the work is not carried out now?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Understanding why the work
  needs to happen now will help you to prioritise and make sure that limited
  resources are targeted to the right activities.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6632690 width=315 style='height:75.0pt;width:236pt'>What
  are the consequences if the work is not carried out correctly?</td>
  <td class=xl6632690 width=396 style='width:297pt'>It is important to
  understand potential legal, financial or reputational consequences if the
  work is not carried out correctly so that you can design a proportionate set
  of assurance activities. The nature and extent of the principal risks that
  the organisation is willing to take in achieving its objectives should also
  determined alongside informing decision making.</td>
 </tr>
 <tr height=83 style='height:62.5pt'>
  <td height=83 class=xl6632690 width=315 style='height:62.5pt;width:236pt'>Who
  is the commissioner, SRO and analytical assurer of this analysis?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Clear lines of
  accountability strengthen assurance processes and make sure that important
  decisions are signed off by the right people. There should be a clear
  understanding of who is responsible for managing, producing and quality
  assuring the analysis in the team.<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6832690 width=315 style='height:100.0pt;width:236pt'>What
  tools and resources will you use during the production process? Are they the
  best for the job?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Before starting an
  analysis, identify all the skills and resources needed to produce the final
  output in a sustainable and reproducible way and to quality assure it at
  every step. The platform used to host the analysis and the software to build
  and run the analysis should be appropriate given uses and risks. For example,
  producing critical outputs in Excel does not comply with best practice and is
  unlikely to be robust or verifiable.</td>
 </tr>
 <tr height=100 style='height:75.0pt'>
  <td height=100 class=xl6632690 width=315 style='height:75.0pt;width:236pt'>Do
  you have the right internal and external resources and capability to deliver
  the analysis?</td>
  <td class=xl6632690 width=396 style='width:297pt'>If the team lacks
  capability, sufficient resource or time, this increases the risk that the
  analysis will not be fit for purpose or sufficiently assured.<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=250 style='height:187.5pt'>
  <td height=250 class=xl6632690 width=315 style='height:187.5pt;width:236pt'>What
  are the anticipated risks of the analysis? Have you discussed this risk with
  the customers?<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6632690 width=396 style='width:297pt'>You must identify potential
  risks and their impact well in advance to enable effective mitigation and
  quicker, confident decision-making. It is also important that users
  understand risks to ensure that their expectations and requirements are met.
  You should document how you have identified and are monitoring and mitigating
  risks.</td>
 </tr>
 <tr height=283 style='height:212.5pt'>
  <td height=283 class=xl6932690 width=315 style='height:212.5pt;width:236pt'>Have
  you developed a contingency plan to put in place if the mitigation plan
  fails?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Risks that would have a
  high impact on the analysis but a low probability of occurring should still
  be accounted for, or else risk serious harm to the public. Without well
  designed contingencies we put the public at risk.</td>
 </tr>
 <tr height=117 style='height:87.5pt'>
  <td height=117 class=xl6832690 width=315 style='height:87.5pt;width:236pt'>Does
  the data and model comply with ethical requirements?<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl6632690 width=396 style='width:297pt'>Analysis must comply with
  ethics standards to ensure public confidence. Data ethics are an essential
  part of any good analysis. You should consider the ethical implications of
  the analysis and how they feed through to use of analysis when you create the
  workflow and report your findings.</td>
 </tr>
 <tr height=167 style='height:125.0pt'>
  <td height=167 class=xl6632690 width=315 style='height:125.0pt;width:236pt'>What
  questions are outside the scope of the analysis?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Limitations affect the
  workings of the analysis and the quality of outputs and what can be done with
  them. By being clear about the limitations of the analysis we ensure that we
  have mitigated or accepted them. Limitations must be documented so everybody
  using the analysis has a shared understanding of them.<span
  style='mso-spacerun:yes'>  </span></td>
 </tr>
 <tr height=133 style='height:100.0pt'>
  <td height=133 class=xl6632690 width=315 style='height:100.0pt;width:236pt'>Will
  internal auditing and peer review be performed?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Internal audit and peer
  review are critical for monitoring and assuring that the analysis is
  performed appropriately and its meeting the required aims and objectives. The
  outcomes of the peer review should be documented and any relevant actions and
  recommendations should be addressed and taken forward.</td>
 </tr>
 <tr height=150 style='height:112.5pt'>
  <td height=150 class=xl6632690 width=315 style='height:112.5pt;width:236pt'>Will
  external experts be involved in development and scruitny of analysis?</td>
  <td class=xl6632690 width=396 style='width:297pt'>Your team should commission
  external specialists to peer review or audit the analysis in proportion to
  the risks around the analysis and its use. They should be.able to draw on
  expertise and experience across government and beyond to get feedback, exchange
  experience and best practices to improve the analysis.</td>
  </tr>
</table>


## AQUA Roles


| Quality Question | Who is responsible for answering this? | Which AQUA book responsibilities have a role? | 
|---------|:-----|------:|
| What question is the analysis trying to answer? | Commissioner, analyst |    The commissioner plays an essential role in communicating the commission and working with the analyst to ensure that an appropriate understanding of the problem is captured. | 
| Why do we need to answer this question? | Commissioner, analyst, analytical assurer |   The analyst must document the purpose of the analysis and the levels of quality and certainty that are required for this purpose. Commissioner and analytical assurer should make sure the work aligns with the stated purpose. |  
| Is the model business critical?   |     |      |  


## Code of Practice for Statistics

| Quality Questions | Which pillar and principle of Code of Practice are relevant here? | 
|---------|:-----|
| What question is the analysis trying to answer?     | V1.1 Statistics producers should maintain and refresh their understanding of the use and potential use of the statistics and data. They should consider the ways in which the statistics might be used and the nature of the decisions that are or could be informed by them.  |  
| Why do we need to answer this question? | V1.1 Statistics producers should maintain and refresh their understanding of the use and potential use of the statistics and data. They should consider the ways in which the statistics might be used and the nature of the decisions that are or could be informed by them. |
| Is the model business critical?   |

## Helpful resources

| Quality Questions | What help is available to answer this question? | 
|---------|:-----|
| What question is the analysis trying to answer?     | AQUA Book, Analysis Functional Standards  |
| Why do we need to answer this question? | Get in touch with user research group or equivalent in your department. |
| Is the model business critical?   | Definition of business critical model. |

## Log of Answers

| Quality Questions | Answer | Is SRO satisfied with the answer provided? | Date answer added | Next review due on |
|:-----|:-----|:-----|:-----|:-----|
| What question is the analysis trying to answer? 
| <p id="content" contenteditable>Enter your answer here... </p>  
| Why do we need to answer this question?  
<td ><p id="content" contenteditable>Enter your answer here...</p></td>   
| Is the model business critical? 
</h2>
  <textarea id="content" contenteditable>Enter your answer here... </textarea> 



<table style="border-collapse: collapse;">
    <th> Quality Questions</th>
    <th> Responsible individual</th>
    <th> Answer</th>
    <th> Is SRO satisfied with the answer provided? (Yes/No) </th>
    <th> Date answer added</th>
     <th> Next review due on</th>

    

  </tr style="border-bottom: 1px solid black;">
  <tr>
    <td>What question is the analysis trying to answer?</td>
    <td> Commissioner, analyst </td>
    <td><p id="content" contenteditable>Enter your answer here... </p></td>
    <td> <a href="https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html">DUCK Book</a> <a href="https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/">RAP</a> </td>
    <td>  </td>
    <td>  </td>
  </tr>
  <tr>
    <td>Why do we need to answer this question?</td>
    <td> Commissioner, analyst, analytical assurer </td>
    <td><p id="content" contenteditable>Enter your answer here... </p></td>
    <td>  </td>
    <td>  </td>
    <td>  </td>
  </tr>
</table>



:::

## II. Design

::: {.panel-tabset}

## Importance 

| Quality Questions | Why do I need to know the answer to this? | 
|---------|:-----|
| Is there a simple description in plain English of what the analysis is for and what it does?     | Writing a plain English description of what the analysis is for and how it works helps the team to assure themselves that they as well as others with no subject related or technical expertise can understand what the analysis is for and broadly how it works.  |   
| Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow? | Setting out a clear summary of the analysis process in a diagram helps the team, users and customers to understand at a glance what the analysis does, where inputs come from, how they are processed and how outputs are generated.  |
| When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination?   | It is important to clearly set out the time requied to perform each stage of analysis from start to finish. It would help the team to evaluate if the current balance of the time split across these stages looks effective and challenge it if the target looks so ambitious.  |

## AQUA Roles


| Quality Question | Who is responsible for answering this? | Which AQUA book responsibilities have a role? | 
|---------|:-----|------:|
| Is there a simple description in plain English of what the analysis is for and what it does? | Analyst, analytical assurer |  Analyst should produce appropriate design documentation. Best practice can include a concept of analysis, user requirements, design specification, functional specification, data dictionary, and test plan. Analytical assurer should be involved. | 
| Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow? | Analyst, analytical assurer |   Analyst should produce appropriate design documentation. Best practice can include a concept of analysis, user requirements, design specification, functional specification, data dictionary, and test plan. Analytical assurer should be involved. |  
| When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination?   |  Commissioner, analyst   |  When commissioning a piece of analysis, a project is established and the typical project trade-offs between time, resources and quality must be made, recorded and communicated to the analyst. The analyst may also have a role in working with the commissioner to establish the optimal balance of these constraints.    |  

## Code of Practice for Statistics

| Quality Questions | Which pillar and principle of Code of Practice are relevant here? | 
|---------|:-----|
| Is there a simple description in plain English of what the analysis is for and what it does?    | V3 Clarity and insight Statistics and data should be presented clearly, explained meaningfully and provide authoritative insights that serve the public good.  |  
| Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow? | V3 Clarity and insight Statistics and data should be presented clearly, explained meaningfully and provide authoritative insights that serve the public good. |
| When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination? |

## Helpful resources

| Quality Questions | What help is available to answer this question? | 
|---------|:-----|
| Is there a simple description in plain English of what the analysis is for and what it does?    | |
| Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow? | |
| When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination?   |  |

## Log of Answers

| Quality Questions |  Answer  | Is SRO satisfied with the answer provided? | Date answer added | Next review due on |
|:------|:-------|:-----|:-----|
| Is there a simple description in plain English of what the analysis is for and what it does?
<p id="content" contenteditable>Enter your answer here... </p>  
| Does the analysis have a logic flowchart which explains the end-to-end conceptual steps in the work flow? 
<td ><p id="content" contenteditable>Enter your answer here...</p></td>   
| When do you expect to start and finish each stage of analysis i.e., data collection, processing, quality assuarnce, analaysis and dissemination?
</h2>
  <textarea id="content" contenteditable>Enter your answer here... </textarea> 

:::

## III. Conducting and Checking Analysis


::: {.panel-tabset}

## Importance 

| Quality Questions | Why do I need to know the answer to this? | 
|---------|:-----|
| How the data used in the analysis will be processed prior to and during use?     | Operations on the data inputs will have wide-ranging effects on processes and outputs. A clear understanding of how these processes affect the workflow is essential for understanding quality.  |   
| Is the data appropriate given the methods selected? | A comprehensive understanding of data inputs is a prerequisite to meeting user needs.  |
| What are the strengths and limitations of the data that you use?   | Not all data can be usd to answer particular research questions. The formatting, the time scale, the granularity must all be assessed and found relevant to the research question. A comprehensive understanding of data inputs is a prerequisite to meeting user needs. Without understanding where data is strong and where it is weak, it is impossible to make meaningful improvements to the analysis and/or the inputs to manage the limitations.     |

## AQUA Roles


| Quality Question | Who is responsible for answering this? | Which AQUA book responsibilities have a role? | 
|---------|:-----|------:|
| How the data used in the analysis will be processed prior to and during use? | Analyst, analytical assurer |    Analyst should collect and manage data. Understand data accuracy and uncertainties. Capture, manage and understand implicit assumptions made. Analytical assurer should be involved.  | 
| Is the data appropriate given the methods selected? | Analyst, analytical assurer, commissioner |   Analyst should understand data accuracy and uncertainties and capture, manage and understand implicit assumptions made. Analyst should engage appropriate subject matter experts, at the appropriate time, when collecting data. NB: The commissioner may be a subject matter expert. Analytical assurere should also be involved. |  
| What are the strengths and limitations of the data that you use?    |  Analyst, analytical assurer   |   If applicable, analyst should undertake parametric analysis to understand the consequences of missing or uncertain data and assumptions. Analytical assurer should be involved.    |  


## Code of Practice for Statistics

| Quality Questions | Which pillar and principle of Code of Practice are relevant here? | 
|---------|:-----|
| How the data used in the analysis will be processed prior to and during use?     | Q1 Suitable data sources Statistics should be based on the most appropriate data to meet intended uses. The impact of any data limitations for use should be assessed, minimised and explained.  |  
| Is the data appropriate given the methods selected? | Q1 Suitable data sources Statistics should be based on the most appropriate data to meet intended uses. The impact of any data limitations for use should be assessed, minimised and explained. |
| What are the strengths and limitations of the data that you use?    | Q1 Suitable data sources Statistics should be based on the most appropriate data to meet intended uses. The impact of any data limitations for use should be assessed, minimised and explained. Q1.5 Potential bias, uncertainty and possible distortive effects in the source data should be identified and the extent of any impact on the statistics should be clearly reported. |

## Helpful resources

| Quality Questions | What help is available to answer this question? | 
|---------|:-----|
| How the data used in the analysis will be processed prior to and during use?     |   |
| Is the data appropriate given the methods selected? |  |
| What are the strengths and limitations of the data that you use?    |  |

## Log of Answers

| Quality Questions | Answer | Is SRO satisfied with the answer provided? | Date answer added | Next review due on |
|:-----|:-----|:-----|:-----|
| How the data used in the analysis will be processed prior to and during use?
 <p id="content" contenteditable>Enter your answer here... </p>  
| Is the data appropriate given the methods selected? 
<td ><p id="content" contenteditable>Enter your answer here...</p></td>   
| What are the strengths and limitations of the data that you use?  
</h2>
  <textarea id="content" contenteditable>Enter your answer here... </textarea> 

:::

## IV. Delivery


::: {.panel-tabset}

## Importance 

| Quality Questions | Why do I need to know the answer to this? | 
|---------|:-----|
| Could you give a clear account of what can and cannot be inferred from your final output?     | A clear understanding of the question is essential for your team to scope out requirements, in understanding the strengths and limitations of the analysis and ensuring that it is fit for purpose. If the question is unclear this risks performing an analysis which does not meet the required user needs.  |   
| Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs? | It is important to describe why each limitation related to data and methods exist, why it cannot be overcome using the chosen approach and what impact does it have on the quality and interpretation of the output produced. Results are of very little value if limitations aren't documented and the rationale for them explained.  |
| Have you sense checked outputs with user groups and stakeholders?  | The credibility of outputs should be checked by experts and sense checked to ensure they are useful. |

## AQUA Roles


| Quality Question | Who is responsible for answering this? | Which AQUA book responsibilities have a role? | 
|---------|:-----|------:|
| Could you give a clear account of what can and cannot be inferred from your final output? | Commissioner |    During the delivery phase, the commissioner has another important role when they receive the interpretation of the results and determine whether it has addressed their request. | 
| Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs? | Commissioner, analytical assurer |   The commissioner must be confident in the quality of the outputs and understand the strengths, limitations and contexts of the analysis so that the results are correctly interpreted. The analytical assurer sign-off provides confidence that analysis risks, limitations and major assumptions are understood by the users of the analysis  |  
| Have you sense checked outputs with user groups and stakeholders?  |     |      |  


## Code of Practice for Statistics

| Quality Questions | Which pillar and principle of Code of Practice are relevant here? | 
|---------|:-----|
| Could you give a clear account of what can and cannot be inferred from your final output?     | Q2.4 Relevant limitations arising from the methods and their application, including bias and uncertainty, should be identified and explained to users. An indication of their likely scale and the steps taken to reduce their impact on the statistics should be included in the explanation.  |  
| Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs? | Q3 Assured quality Producers of statistics and data should explain clearly how they assure themselves that statistics and data are accurate, reliable, coherent and timely. Q1.5 Potential bias, uncertainty and possible distortive effects in the source data should be identified and the extent of any impact on the statistics should be clearly reported. Q3.1 Statistics should be produced to a level of quality that meets users’ needs. The strengths and limitations of the statistics and data should be considered in relation to different uses, and clearly explained alongside the statistics. |
| Have you sense checked outputs with user groups and stakeholders?   | Q3 Assured quality Producers of statistics and data should explain clearly how they assure themselves that statistics and data are accurate, reliable, coherent and timely. |

## Helpful resources

| Quality Questions | What help is available to answer this question? | 
|---------|:-----|
| Could you give a clear account of what can and cannot be inferred from your final output?     |   |
| Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs? |  |
| Have you sense checked outputs with user groups and stakeholders?  |  |

## Log of Answers

| Quality Questions | Answer | Is SRO satisfied with the answer provided? | Date answer added | Next review due on |
|:-----|:-----|:-----|:-----|
| Could you give a clear account of what can and cannot be inferred from your final output?
 <p id="content" contenteditable>Enter your answer here... </p>  
| Have you assessed the impact of the data and model limitations and set out how they will affect the quality and use of the outputs?  
<td ><p id="content" contenteditable>Enter your answer here...</p></td>   
| Have you sense checked outputs with user groups and stakeholders?
</h2>
  <textarea id="content" contenteditable>Enter your answer here... </textarea> 

:::


## Feedback 

<iframe width="640px" height="480px" src="https://forms.office.com/Pages/ResponsePage.aspx?id=vweIB4LOiEa84A2BFoTcRkDkgdjwbsZIk809xX5dKNlUNjlFOEJITFdITDdQMTc3ODBaVTdLMzdLTC4u&embed=true" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>